#!/bin/bash

#######################################################################################################
# random-programs weather - a simple bash script for getting the weather                             #
# Written in 2021 by xf8b <unknownperson102424@pm.me>                                                #
# To the extent possible under law, the author has dedicated all copyright                           #
# and related and neighboring rights to this software to the public domain worldwide.                #
# This software is distributed without any warranty.                                                 #
# You should have also received a copy of the CC0 Public Domain Dedication along with this software. #
# If not, see <https://creativecommons.org/publicdomain/zero/1.0/>.                                  #
######################################################################################################

# util functions

function blank() {
  # if the first input is not empty and is not a space, return false
  # else return true
  if [ -n "$1" ] && [ "$1" != " " ]; then
    echo false
  else
    echo true
  fi
}

# the actual code

# read user input
read -rp "Which version of wttr.in should be used? (press enter for v1) " version
read -rp "Which place's weather should be shown? (press enter for current location) " place
read -rp "What arguments should be added? (press enter for none) " arguments

# base url
url="v$version.wttr.in"

# if a place is specified, use that place
if [ "$(blank "$place")" ]; then
  url+="/$place"
fi

# if arguments are specified, use those arguments
if [ "$(blank "$arguments")" ]; then
  url+="?$arguments"
fi

# create empty line between input questions and the result
echo

# get the result
curl "$url"
